### ISSUE TITLE
Video (picture) doesn't play

### ISSUE THREAD

**Issue by moneytoo** [dburckh/ExoPlayer#11]
Attached sample plays, but without picture. The picture works when remuxing to other container (mkv).

Sample: [mmv-20.zip](https://github.com/dburckh/ExoPlayer/files/7963754/mmv-20.zip)

**Comment by dburckh** [comment]
This guy is using AVC pic_order_count_type 2, I currently only support type 0.  I'll have a look.

**Comment by dburckh** [comment]
I added support for pic_order_count_type 2.  It works slightly better now.  It still doesn't work right because it's 30 FPS and it's muxed at 120 FPS.  Not sure if I want to support this madness, or just call it a day.  :)

**Comment by dburckh** [comment]
This file is now working.  I added code to use the standard linear (Chunk) clock when there are not B-Frames present.  This has the bonus of reducing the overhead.  Unfortunately, if any file that use B frames and muxes in this manner will be broken and difficult to fix.
