### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by moneytoo** [dburckh/ExoPlayer#9]
Another avi file which is failing to play: [pyth.avi](https://brouken.com/tmp/pyth.avi) (First frame is rendered but the playback never starts, total video duration is negative.)

The avi extractor on my Samsung phone is able to handle it but it could be quite possible similar issue to #5.

**Comment by dburckh** [comment]
Playback bug was caused by large scale and new offset logic.

This file also has a known muxer bug where the idx1 offset is incorrect.  Add work-around for that too.

Pushed changes.  

FYI:  Default branch is now "avi", not dev-v2.

**Comment by moneytoo** [comment]
Yep, it plays now. Great!
